# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Video with background image
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  video: bookshop:simple/wistia-video
  image: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  image: http://placekitten.com/1280/740

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
