# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: Wistia video
  description: Video player
  icon: ondemand_video
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  video_id: ""
  playerColor: ff0000
  controlsVisibleOnLoad: false
  volumeControl: false
  autoPlay: true
  muted: true
  endVideoBehavior: loop
  fitStrategy: cover

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  video_id: tv2o9042dw

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
