baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Papercut - components '

[module]
replacements = "local/component-library -> ../component-library"
[module.hugoVersion]
extended = true
min = "0.86.1"

[[module.imports]]
path = 'local/component-library'

[[module.imports]]
path = 'github.com/cloudcannon/bookshop/hugo/v3'

[[module.mounts]]
source = "component-library"
target = "layouts/partials/bookshop"

[[module.mounts]]
source = "component-library"
target = "assets/bookshop"

[[module.mounts]]
source = "data"
target = "data"

[[module.mounts]]
source = "layouts"
target = "layouts"

[[module.mounts]]
source = "assets"
target = "assets"

# Test change