# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Simple Accordian"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  title: 
  icon_image: 
  body_content: 

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  title: "In-Product Marketing Toolkit"
  body_content: "Equip your business to tell its sustainability story with customized website components, social media templates, and other content"

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
