# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Lottie-player"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  autoplay: true
  loop: true
  lottie_file: ""


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  lottie_file: https://assets3.lottiefiles.com/packages/lf20_UJNc2t.json

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  lottie_file:
    type: url