# Metadata about this component, to be used in the CMS
spec:
  structures:
  label: "Generic Link"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content: 
  url:
  open_in_new_tab: true


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  content: "Learn more about papercut grows"
  url: "#"
  open_in_new_tab: true


# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
