# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Sections Banner-with-video-background"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: 
  subheading:
  logo_image_path:
  logo_image_alt_tag: 
  link: bookshop:generic/link
  background_video: bookshop:simple/background-wistia-video
  fall_back_background_image: 
  content_alignment: "left"
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:


# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  content_alignment:
    type: select
    options:
      values:
        - "left"
        - "right"
