# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Sections Carousel"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  slides: [bookshop:simple/slider-card]


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  slides:
    - title: "HP carbon neutral offering"
      body_text: "HP's Sustainable Impact creates lasting, positive change for the planet, our people, and the communities where we live, work, and do business."
      url: "#"



# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:

